// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/customhomelink"
)

// CustomHomeLinkCreate is the builder for creating a CustomHomeLink entity.
type CustomHomeLinkCreate struct {
	config
	mutation *CustomHomeLinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *CustomHomeLinkCreate) SetTitle(v string) *CustomHomeLinkCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CustomHomeLinkCreate) SetDescription(v string) *CustomHomeLinkCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CustomHomeLinkCreate) SetNillableDescription(v *string) *CustomHomeLinkCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *CustomHomeLinkCreate) SetURL(v string) *CustomHomeLinkCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetOpenInNewWindow sets the "open_in_new_window" field.
func (_c *CustomHomeLinkCreate) SetOpenInNewWindow(v bool) *CustomHomeLinkCreate {
	_c.mutation.SetOpenInNewWindow(v)
	return _c
}

// SetNillableOpenInNewWindow sets the "open_in_new_window" field if the given value is not nil.
func (_c *CustomHomeLinkCreate) SetNillableOpenInNewWindow(v *bool) *CustomHomeLinkCreate {
	if v != nil {
		_c.SetOpenInNewWindow(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *CustomHomeLinkCreate) SetSortOrder(v int) *CustomHomeLinkCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *CustomHomeLinkCreate) SetNillableSortOrder(v *int) *CustomHomeLinkCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomHomeLinkCreate) SetCreatedAt(v time.Time) *CustomHomeLinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomHomeLinkCreate) SetNillableCreatedAt(v *time.Time) *CustomHomeLinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomHomeLinkCreate) SetUpdatedAt(v time.Time) *CustomHomeLinkCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomHomeLinkCreate) SetNillableUpdatedAt(v *time.Time) *CustomHomeLinkCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CustomHomeLinkMutation object of the builder.
func (_c *CustomHomeLinkCreate) Mutation() *CustomHomeLinkMutation {
	return _c.mutation
}

// Save creates the CustomHomeLink in the database.
func (_c *CustomHomeLinkCreate) Save(ctx context.Context) (*CustomHomeLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomHomeLinkCreate) SaveX(ctx context.Context) *CustomHomeLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomHomeLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomHomeLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomHomeLinkCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := customhomelink.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.OpenInNewWindow(); !ok {
		v := customhomelink.DefaultOpenInNewWindow
		_c.mutation.SetOpenInNewWindow(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := customhomelink.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := customhomelink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := customhomelink.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomHomeLinkCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "CustomHomeLink.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := customhomelink.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CustomHomeLink.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "CustomHomeLink.description"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "CustomHomeLink.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := customhomelink.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "CustomHomeLink.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OpenInNewWindow(); !ok {
		return &ValidationError{Name: "open_in_new_window", err: errors.New(`ent: missing required field "CustomHomeLink.open_in_new_window"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "CustomHomeLink.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomHomeLink.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CustomHomeLink.updated_at"`)}
	}
	return nil
}

func (_c *CustomHomeLinkCreate) sqlSave(ctx context.Context) (*CustomHomeLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomHomeLinkCreate) createSpec() (*CustomHomeLink, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomHomeLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customhomelink.Table, sqlgraph.NewFieldSpec(customhomelink.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(customhomelink.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(customhomelink.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(customhomelink.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.OpenInNewWindow(); ok {
		_spec.SetField(customhomelink.FieldOpenInNewWindow, field.TypeBool, value)
		_node.OpenInNewWindow = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(customhomelink.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(customhomelink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(customhomelink.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomHomeLink.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomHomeLinkUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomHomeLinkCreate) OnConflict(opts ...sql.ConflictOption) *CustomHomeLinkUpsertOne {
	_c.conflict = opts
	return &CustomHomeLinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomHomeLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomHomeLinkCreate) OnConflictColumns(columns ...string) *CustomHomeLinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomHomeLinkUpsertOne{
		create: _c,
	}
}

type (
	// CustomHomeLinkUpsertOne is the builder for "upsert"-ing
	//  one CustomHomeLink node.
	CustomHomeLinkUpsertOne struct {
		create *CustomHomeLinkCreate
	}

	// CustomHomeLinkUpsert is the "OnConflict" setter.
	CustomHomeLinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *CustomHomeLinkUpsert) SetTitle(v string) *CustomHomeLinkUpsert {
	u.Set(customhomelink.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CustomHomeLinkUpsert) UpdateTitle() *CustomHomeLinkUpsert {
	u.SetExcluded(customhomelink.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *CustomHomeLinkUpsert) SetDescription(v string) *CustomHomeLinkUpsert {
	u.Set(customhomelink.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CustomHomeLinkUpsert) UpdateDescription() *CustomHomeLinkUpsert {
	u.SetExcluded(customhomelink.FieldDescription)
	return u
}

// SetURL sets the "url" field.
func (u *CustomHomeLinkUpsert) SetURL(v string) *CustomHomeLinkUpsert {
	u.Set(customhomelink.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *CustomHomeLinkUpsert) UpdateURL() *CustomHomeLinkUpsert {
	u.SetExcluded(customhomelink.FieldURL)
	return u
}

// SetOpenInNewWindow sets the "open_in_new_window" field.
func (u *CustomHomeLinkUpsert) SetOpenInNewWindow(v bool) *CustomHomeLinkUpsert {
	u.Set(customhomelink.FieldOpenInNewWindow, v)
	return u
}

// UpdateOpenInNewWindow sets the "open_in_new_window" field to the value that was provided on create.
func (u *CustomHomeLinkUpsert) UpdateOpenInNewWindow() *CustomHomeLinkUpsert {
	u.SetExcluded(customhomelink.FieldOpenInNewWindow)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *CustomHomeLinkUpsert) SetSortOrder(v int) *CustomHomeLinkUpsert {
	u.Set(customhomelink.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CustomHomeLinkUpsert) UpdateSortOrder() *CustomHomeLinkUpsert {
	u.SetExcluded(customhomelink.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CustomHomeLinkUpsert) AddSortOrder(v int) *CustomHomeLinkUpsert {
	u.Add(customhomelink.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomHomeLinkUpsert) SetUpdatedAt(v time.Time) *CustomHomeLinkUpsert {
	u.Set(customhomelink.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomHomeLinkUpsert) UpdateUpdatedAt() *CustomHomeLinkUpsert {
	u.SetExcluded(customhomelink.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CustomHomeLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomHomeLinkUpsertOne) UpdateNewValues() *CustomHomeLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(customhomelink.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomHomeLink.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomHomeLinkUpsertOne) Ignore() *CustomHomeLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomHomeLinkUpsertOne) DoNothing() *CustomHomeLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomHomeLinkCreate.OnConflict
// documentation for more info.
func (u *CustomHomeLinkUpsertOne) Update(set func(*CustomHomeLinkUpsert)) *CustomHomeLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomHomeLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *CustomHomeLinkUpsertOne) SetTitle(v string) *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertOne) UpdateTitle() *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *CustomHomeLinkUpsertOne) SetDescription(v string) *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertOne) UpdateDescription() *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateDescription()
	})
}

// SetURL sets the "url" field.
func (u *CustomHomeLinkUpsertOne) SetURL(v string) *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertOne) UpdateURL() *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateURL()
	})
}

// SetOpenInNewWindow sets the "open_in_new_window" field.
func (u *CustomHomeLinkUpsertOne) SetOpenInNewWindow(v bool) *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetOpenInNewWindow(v)
	})
}

// UpdateOpenInNewWindow sets the "open_in_new_window" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertOne) UpdateOpenInNewWindow() *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateOpenInNewWindow()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CustomHomeLinkUpsertOne) SetSortOrder(v int) *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CustomHomeLinkUpsertOne) AddSortOrder(v int) *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertOne) UpdateSortOrder() *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomHomeLinkUpsertOne) SetUpdatedAt(v time.Time) *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertOne) UpdateUpdatedAt() *CustomHomeLinkUpsertOne {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CustomHomeLinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomHomeLinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomHomeLinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomHomeLinkUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomHomeLinkUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomHomeLinkCreateBulk is the builder for creating many CustomHomeLink entities in bulk.
type CustomHomeLinkCreateBulk struct {
	config
	err      error
	builders []*CustomHomeLinkCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomHomeLink entities in the database.
func (_c *CustomHomeLinkCreateBulk) Save(ctx context.Context) ([]*CustomHomeLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomHomeLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomHomeLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomHomeLinkCreateBulk) SaveX(ctx context.Context) []*CustomHomeLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomHomeLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomHomeLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomHomeLink.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomHomeLinkUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomHomeLinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomHomeLinkUpsertBulk {
	_c.conflict = opts
	return &CustomHomeLinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomHomeLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomHomeLinkCreateBulk) OnConflictColumns(columns ...string) *CustomHomeLinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomHomeLinkUpsertBulk{
		create: _c,
	}
}

// CustomHomeLinkUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomHomeLink nodes.
type CustomHomeLinkUpsertBulk struct {
	create *CustomHomeLinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomHomeLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomHomeLinkUpsertBulk) UpdateNewValues() *CustomHomeLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(customhomelink.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomHomeLink.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomHomeLinkUpsertBulk) Ignore() *CustomHomeLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomHomeLinkUpsertBulk) DoNothing() *CustomHomeLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomHomeLinkCreateBulk.OnConflict
// documentation for more info.
func (u *CustomHomeLinkUpsertBulk) Update(set func(*CustomHomeLinkUpsert)) *CustomHomeLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomHomeLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *CustomHomeLinkUpsertBulk) SetTitle(v string) *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertBulk) UpdateTitle() *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *CustomHomeLinkUpsertBulk) SetDescription(v string) *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertBulk) UpdateDescription() *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateDescription()
	})
}

// SetURL sets the "url" field.
func (u *CustomHomeLinkUpsertBulk) SetURL(v string) *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertBulk) UpdateURL() *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateURL()
	})
}

// SetOpenInNewWindow sets the "open_in_new_window" field.
func (u *CustomHomeLinkUpsertBulk) SetOpenInNewWindow(v bool) *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetOpenInNewWindow(v)
	})
}

// UpdateOpenInNewWindow sets the "open_in_new_window" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertBulk) UpdateOpenInNewWindow() *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateOpenInNewWindow()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *CustomHomeLinkUpsertBulk) SetSortOrder(v int) *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *CustomHomeLinkUpsertBulk) AddSortOrder(v int) *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertBulk) UpdateSortOrder() *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomHomeLinkUpsertBulk) SetUpdatedAt(v time.Time) *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomHomeLinkUpsertBulk) UpdateUpdatedAt() *CustomHomeLinkUpsertBulk {
	return u.Update(func(s *CustomHomeLinkUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CustomHomeLinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomHomeLinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomHomeLinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomHomeLinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
