// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/customhomelink"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CustomHomeLinkUpdate is the builder for updating CustomHomeLink entities.
type CustomHomeLinkUpdate struct {
	config
	hooks    []Hook
	mutation *CustomHomeLinkMutation
}

// Where appends a list predicates to the CustomHomeLinkUpdate builder.
func (_u *CustomHomeLinkUpdate) Where(ps ...predicate.CustomHomeLink) *CustomHomeLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *CustomHomeLinkUpdate) SetTitle(v string) *CustomHomeLinkUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CustomHomeLinkUpdate) SetNillableTitle(v *string) *CustomHomeLinkUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CustomHomeLinkUpdate) SetDescription(v string) *CustomHomeLinkUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CustomHomeLinkUpdate) SetNillableDescription(v *string) *CustomHomeLinkUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *CustomHomeLinkUpdate) SetURL(v string) *CustomHomeLinkUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *CustomHomeLinkUpdate) SetNillableURL(v *string) *CustomHomeLinkUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetOpenInNewWindow sets the "open_in_new_window" field.
func (_u *CustomHomeLinkUpdate) SetOpenInNewWindow(v bool) *CustomHomeLinkUpdate {
	_u.mutation.SetOpenInNewWindow(v)
	return _u
}

// SetNillableOpenInNewWindow sets the "open_in_new_window" field if the given value is not nil.
func (_u *CustomHomeLinkUpdate) SetNillableOpenInNewWindow(v *bool) *CustomHomeLinkUpdate {
	if v != nil {
		_u.SetOpenInNewWindow(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CustomHomeLinkUpdate) SetSortOrder(v int) *CustomHomeLinkUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CustomHomeLinkUpdate) SetNillableSortOrder(v *int) *CustomHomeLinkUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CustomHomeLinkUpdate) AddSortOrder(v int) *CustomHomeLinkUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomHomeLinkUpdate) SetUpdatedAt(v time.Time) *CustomHomeLinkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CustomHomeLinkMutation object of the builder.
func (_u *CustomHomeLinkUpdate) Mutation() *CustomHomeLinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomHomeLinkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomHomeLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomHomeLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomHomeLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomHomeLinkUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customhomelink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomHomeLinkUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := customhomelink.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CustomHomeLink.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := customhomelink.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "CustomHomeLink.url": %w`, err)}
		}
	}
	return nil
}

func (_u *CustomHomeLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customhomelink.Table, customhomelink.Columns, sqlgraph.NewFieldSpec(customhomelink.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(customhomelink.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(customhomelink.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(customhomelink.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpenInNewWindow(); ok {
		_spec.SetField(customhomelink.FieldOpenInNewWindow, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(customhomelink.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(customhomelink.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customhomelink.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customhomelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomHomeLinkUpdateOne is the builder for updating a single CustomHomeLink entity.
type CustomHomeLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomHomeLinkMutation
}

// SetTitle sets the "title" field.
func (_u *CustomHomeLinkUpdateOne) SetTitle(v string) *CustomHomeLinkUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CustomHomeLinkUpdateOne) SetNillableTitle(v *string) *CustomHomeLinkUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CustomHomeLinkUpdateOne) SetDescription(v string) *CustomHomeLinkUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CustomHomeLinkUpdateOne) SetNillableDescription(v *string) *CustomHomeLinkUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *CustomHomeLinkUpdateOne) SetURL(v string) *CustomHomeLinkUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *CustomHomeLinkUpdateOne) SetNillableURL(v *string) *CustomHomeLinkUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetOpenInNewWindow sets the "open_in_new_window" field.
func (_u *CustomHomeLinkUpdateOne) SetOpenInNewWindow(v bool) *CustomHomeLinkUpdateOne {
	_u.mutation.SetOpenInNewWindow(v)
	return _u
}

// SetNillableOpenInNewWindow sets the "open_in_new_window" field if the given value is not nil.
func (_u *CustomHomeLinkUpdateOne) SetNillableOpenInNewWindow(v *bool) *CustomHomeLinkUpdateOne {
	if v != nil {
		_u.SetOpenInNewWindow(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CustomHomeLinkUpdateOne) SetSortOrder(v int) *CustomHomeLinkUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CustomHomeLinkUpdateOne) SetNillableSortOrder(v *int) *CustomHomeLinkUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CustomHomeLinkUpdateOne) AddSortOrder(v int) *CustomHomeLinkUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomHomeLinkUpdateOne) SetUpdatedAt(v time.Time) *CustomHomeLinkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CustomHomeLinkMutation object of the builder.
func (_u *CustomHomeLinkUpdateOne) Mutation() *CustomHomeLinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the CustomHomeLinkUpdate builder.
func (_u *CustomHomeLinkUpdateOne) Where(ps ...predicate.CustomHomeLink) *CustomHomeLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomHomeLinkUpdateOne) Select(field string, fields ...string) *CustomHomeLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomHomeLink entity.
func (_u *CustomHomeLinkUpdateOne) Save(ctx context.Context) (*CustomHomeLink, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomHomeLinkUpdateOne) SaveX(ctx context.Context) *CustomHomeLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomHomeLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomHomeLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomHomeLinkUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customhomelink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomHomeLinkUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := customhomelink.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "CustomHomeLink.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := customhomelink.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "CustomHomeLink.url": %w`, err)}
		}
	}
	return nil
}

func (_u *CustomHomeLinkUpdateOne) sqlSave(ctx context.Context) (_node *CustomHomeLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customhomelink.Table, customhomelink.Columns, sqlgraph.NewFieldSpec(customhomelink.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CustomHomeLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customhomelink.FieldID)
		for _, f := range fields {
			if !customhomelink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != customhomelink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(customhomelink.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(customhomelink.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(customhomelink.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.OpenInNewWindow(); ok {
		_spec.SetField(customhomelink.FieldOpenInNewWindow, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(customhomelink.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(customhomelink.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customhomelink.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CustomHomeLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customhomelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
