// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
)

// SupportTicketMessageUpdate is the builder for updating SupportTicketMessage entities.
type SupportTicketMessageUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketMessageMutation
}

// Where appends a list predicates to the SupportTicketMessageUpdate builder.
func (_u *SupportTicketMessageUpdate) Where(ps ...predicate.SupportTicketMessage) *SupportTicketMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportTicketMessageUpdate) SetTicketID(v int64) *SupportTicketMessageUpdate {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableTicketID(v *int64) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *SupportTicketMessageUpdate) SetAuthorID(v int64) *SupportTicketMessageUpdate {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableAuthorID(v *int64) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *SupportTicketMessageUpdate) AddAuthorID(v int64) *SupportTicketMessageUpdate {
	_u.mutation.AddAuthorID(v)
	return _u
}

// ClearAuthorID clears the value of the "author_id" field.
func (_u *SupportTicketMessageUpdate) ClearAuthorID() *SupportTicketMessageUpdate {
	_u.mutation.ClearAuthorID()
	return _u
}

// SetAuthorRole sets the "author_role" field.
func (_u *SupportTicketMessageUpdate) SetAuthorRole(v string) *SupportTicketMessageUpdate {
	_u.mutation.SetAuthorRole(v)
	return _u
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableAuthorRole(v *string) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetAuthorRole(*v)
	}
	return _u
}

// SetAuthorEmail sets the "author_email" field.
func (_u *SupportTicketMessageUpdate) SetAuthorEmail(v string) *SupportTicketMessageUpdate {
	_u.mutation.SetAuthorEmail(v)
	return _u
}

// SetNillableAuthorEmail sets the "author_email" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableAuthorEmail(v *string) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetAuthorEmail(*v)
	}
	return _u
}

// ClearAuthorEmail clears the value of the "author_email" field.
func (_u *SupportTicketMessageUpdate) ClearAuthorEmail() *SupportTicketMessageUpdate {
	_u.mutation.ClearAuthorEmail()
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *SupportTicketMessageUpdate) SetAuthorName(v string) *SupportTicketMessageUpdate {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableAuthorName(v *string) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// ClearAuthorName clears the value of the "author_name" field.
func (_u *SupportTicketMessageUpdate) ClearAuthorName() *SupportTicketMessageUpdate {
	_u.mutation.ClearAuthorName()
	return _u
}

// SetContent sets the "content" field.
func (_u *SupportTicketMessageUpdate) SetContent(v string) *SupportTicketMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SupportTicketMessageUpdate) SetNillableContent(v *string) *SupportTicketMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTicket sets the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketMessageUpdate) SetTicket(v *SupportTicket) *SupportTicketMessageUpdate {
	return _u.SetTicketID(v.ID)
}

// Mutation returns the SupportTicketMessageMutation object of the builder.
func (_u *SupportTicketMessageUpdate) Mutation() *SupportTicketMessageMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketMessageUpdate) ClearTicket() *SupportTicketMessageUpdate {
	_u.mutation.ClearTicket()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketMessageUpdate) check() error {
	if v, ok := _u.mutation.AuthorRole(); ok {
		if err := supportticketmessage.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorEmail(); ok {
		if err := supportticketmessage.AuthorEmailValidator(v); err != nil {
			return &ValidationError{Name: "author_email", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorName(); ok {
		if err := supportticketmessage.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := supportticketmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.content": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketMessage.ticket"`)
	}
	return nil
}

func (_u *SupportTicketMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketmessage.Table, supportticketmessage.Columns, sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(supportticketmessage.FieldAuthorID, field.TypeInt64, value)
	}
	if _u.mutation.AuthorIDCleared() {
		_spec.ClearField(supportticketmessage.FieldAuthorID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AuthorRole(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorEmail(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorEmail, field.TypeString, value)
	}
	if _u.mutation.AuthorEmailCleared() {
		_spec.ClearField(supportticketmessage.FieldAuthorEmail, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorName, field.TypeString, value)
	}
	if _u.mutation.AuthorNameCleared() {
		_spec.ClearField(supportticketmessage.FieldAuthorName, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(supportticketmessage.FieldContent, field.TypeString, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.TicketTable,
			Columns: []string{supportticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.TicketTable,
			Columns: []string{supportticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketMessageUpdateOne is the builder for updating a single SupportTicketMessage entity.
type SupportTicketMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketMessageMutation
}

// SetTicketID sets the "ticket_id" field.
func (_u *SupportTicketMessageUpdateOne) SetTicketID(v int64) *SupportTicketMessageUpdateOne {
	_u.mutation.SetTicketID(v)
	return _u
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableTicketID(v *int64) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetTicketID(*v)
	}
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *SupportTicketMessageUpdateOne) SetAuthorID(v int64) *SupportTicketMessageUpdateOne {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableAuthorID(v *int64) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *SupportTicketMessageUpdateOne) AddAuthorID(v int64) *SupportTicketMessageUpdateOne {
	_u.mutation.AddAuthorID(v)
	return _u
}

// ClearAuthorID clears the value of the "author_id" field.
func (_u *SupportTicketMessageUpdateOne) ClearAuthorID() *SupportTicketMessageUpdateOne {
	_u.mutation.ClearAuthorID()
	return _u
}

// SetAuthorRole sets the "author_role" field.
func (_u *SupportTicketMessageUpdateOne) SetAuthorRole(v string) *SupportTicketMessageUpdateOne {
	_u.mutation.SetAuthorRole(v)
	return _u
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableAuthorRole(v *string) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetAuthorRole(*v)
	}
	return _u
}

// SetAuthorEmail sets the "author_email" field.
func (_u *SupportTicketMessageUpdateOne) SetAuthorEmail(v string) *SupportTicketMessageUpdateOne {
	_u.mutation.SetAuthorEmail(v)
	return _u
}

// SetNillableAuthorEmail sets the "author_email" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableAuthorEmail(v *string) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetAuthorEmail(*v)
	}
	return _u
}

// ClearAuthorEmail clears the value of the "author_email" field.
func (_u *SupportTicketMessageUpdateOne) ClearAuthorEmail() *SupportTicketMessageUpdateOne {
	_u.mutation.ClearAuthorEmail()
	return _u
}

// SetAuthorName sets the "author_name" field.
func (_u *SupportTicketMessageUpdateOne) SetAuthorName(v string) *SupportTicketMessageUpdateOne {
	_u.mutation.SetAuthorName(v)
	return _u
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableAuthorName(v *string) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetAuthorName(*v)
	}
	return _u
}

// ClearAuthorName clears the value of the "author_name" field.
func (_u *SupportTicketMessageUpdateOne) ClearAuthorName() *SupportTicketMessageUpdateOne {
	_u.mutation.ClearAuthorName()
	return _u
}

// SetContent sets the "content" field.
func (_u *SupportTicketMessageUpdateOne) SetContent(v string) *SupportTicketMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SupportTicketMessageUpdateOne) SetNillableContent(v *string) *SupportTicketMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetTicket sets the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketMessageUpdateOne) SetTicket(v *SupportTicket) *SupportTicketMessageUpdateOne {
	return _u.SetTicketID(v.ID)
}

// Mutation returns the SupportTicketMessageMutation object of the builder.
func (_u *SupportTicketMessageUpdateOne) Mutation() *SupportTicketMessageMutation {
	return _u.mutation
}

// ClearTicket clears the "ticket" edge to the SupportTicket entity.
func (_u *SupportTicketMessageUpdateOne) ClearTicket() *SupportTicketMessageUpdateOne {
	_u.mutation.ClearTicket()
	return _u
}

// Where appends a list predicates to the SupportTicketMessageUpdate builder.
func (_u *SupportTicketMessageUpdateOne) Where(ps ...predicate.SupportTicketMessage) *SupportTicketMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketMessageUpdateOne) Select(field string, fields ...string) *SupportTicketMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicketMessage entity.
func (_u *SupportTicketMessageUpdateOne) Save(ctx context.Context) (*SupportTicketMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketMessageUpdateOne) SaveX(ctx context.Context) *SupportTicketMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketMessageUpdateOne) check() error {
	if v, ok := _u.mutation.AuthorRole(); ok {
		if err := supportticketmessage.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorEmail(); ok {
		if err := supportticketmessage.AuthorEmailValidator(v); err != nil {
			return &ValidationError{Name: "author_email", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorName(); ok {
		if err := supportticketmessage.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := supportticketmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.content": %w`, err)}
		}
	}
	if _u.mutation.TicketCleared() && len(_u.mutation.TicketIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicketMessage.ticket"`)
	}
	return nil
}

func (_u *SupportTicketMessageUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicketMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticketmessage.Table, supportticketmessage.Columns, sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicketMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticketmessage.FieldID)
		for _, f := range fields {
			if !supportticketmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticketmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(supportticketmessage.FieldAuthorID, field.TypeInt64, value)
	}
	if _u.mutation.AuthorIDCleared() {
		_spec.ClearField(supportticketmessage.FieldAuthorID, field.TypeInt64)
	}
	if value, ok := _u.mutation.AuthorRole(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthorEmail(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorEmail, field.TypeString, value)
	}
	if _u.mutation.AuthorEmailCleared() {
		_spec.ClearField(supportticketmessage.FieldAuthorEmail, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorName(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorName, field.TypeString, value)
	}
	if _u.mutation.AuthorNameCleared() {
		_spec.ClearField(supportticketmessage.FieldAuthorName, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(supportticketmessage.FieldContent, field.TypeString, value)
	}
	if _u.mutation.TicketCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.TicketTable,
			Columns: []string{supportticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.TicketTable,
			Columns: []string{supportticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportTicketMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticketmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
