// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
)

// SupportTicketMessageCreate is the builder for creating a SupportTicketMessage entity.
type SupportTicketMessageCreate struct {
	config
	mutation *SupportTicketMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTicketID sets the "ticket_id" field.
func (_c *SupportTicketMessageCreate) SetTicketID(v int64) *SupportTicketMessageCreate {
	_c.mutation.SetTicketID(v)
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *SupportTicketMessageCreate) SetAuthorID(v int64) *SupportTicketMessageCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_c *SupportTicketMessageCreate) SetNillableAuthorID(v *int64) *SupportTicketMessageCreate {
	if v != nil {
		_c.SetAuthorID(*v)
	}
	return _c
}

// SetAuthorRole sets the "author_role" field.
func (_c *SupportTicketMessageCreate) SetAuthorRole(v string) *SupportTicketMessageCreate {
	_c.mutation.SetAuthorRole(v)
	return _c
}

// SetNillableAuthorRole sets the "author_role" field if the given value is not nil.
func (_c *SupportTicketMessageCreate) SetNillableAuthorRole(v *string) *SupportTicketMessageCreate {
	if v != nil {
		_c.SetAuthorRole(*v)
	}
	return _c
}

// SetAuthorEmail sets the "author_email" field.
func (_c *SupportTicketMessageCreate) SetAuthorEmail(v string) *SupportTicketMessageCreate {
	_c.mutation.SetAuthorEmail(v)
	return _c
}

// SetNillableAuthorEmail sets the "author_email" field if the given value is not nil.
func (_c *SupportTicketMessageCreate) SetNillableAuthorEmail(v *string) *SupportTicketMessageCreate {
	if v != nil {
		_c.SetAuthorEmail(*v)
	}
	return _c
}

// SetAuthorName sets the "author_name" field.
func (_c *SupportTicketMessageCreate) SetAuthorName(v string) *SupportTicketMessageCreate {
	_c.mutation.SetAuthorName(v)
	return _c
}

// SetNillableAuthorName sets the "author_name" field if the given value is not nil.
func (_c *SupportTicketMessageCreate) SetNillableAuthorName(v *string) *SupportTicketMessageCreate {
	if v != nil {
		_c.SetAuthorName(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *SupportTicketMessageCreate) SetContent(v string) *SupportTicketMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupportTicketMessageCreate) SetCreatedAt(v time.Time) *SupportTicketMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupportTicketMessageCreate) SetNillableCreatedAt(v *time.Time) *SupportTicketMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTicket sets the "ticket" edge to the SupportTicket entity.
func (_c *SupportTicketMessageCreate) SetTicket(v *SupportTicket) *SupportTicketMessageCreate {
	return _c.SetTicketID(v.ID)
}

// Mutation returns the SupportTicketMessageMutation object of the builder.
func (_c *SupportTicketMessageCreate) Mutation() *SupportTicketMessageMutation {
	return _c.mutation
}

// Save creates the SupportTicketMessage in the database.
func (_c *SupportTicketMessageCreate) Save(ctx context.Context) (*SupportTicketMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupportTicketMessageCreate) SaveX(ctx context.Context) *SupportTicketMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupportTicketMessageCreate) defaults() {
	if _, ok := _c.mutation.AuthorRole(); !ok {
		v := supportticketmessage.DefaultAuthorRole
		_c.mutation.SetAuthorRole(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supportticketmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupportTicketMessageCreate) check() error {
	if _, ok := _c.mutation.TicketID(); !ok {
		return &ValidationError{Name: "ticket_id", err: errors.New(`ent: missing required field "SupportTicketMessage.ticket_id"`)}
	}
	if _, ok := _c.mutation.AuthorRole(); !ok {
		return &ValidationError{Name: "author_role", err: errors.New(`ent: missing required field "SupportTicketMessage.author_role"`)}
	}
	if v, ok := _c.mutation.AuthorRole(); ok {
		if err := supportticketmessage.AuthorRoleValidator(v); err != nil {
			return &ValidationError{Name: "author_role", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_role": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AuthorEmail(); ok {
		if err := supportticketmessage.AuthorEmailValidator(v); err != nil {
			return &ValidationError{Name: "author_email", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AuthorName(); ok {
		if err := supportticketmessage.AuthorNameValidator(v); err != nil {
			return &ValidationError{Name: "author_name", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.author_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "SupportTicketMessage.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := supportticketmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "SupportTicketMessage.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportTicketMessage.created_at"`)}
	}
	if len(_c.mutation.TicketIDs()) == 0 {
		return &ValidationError{Name: "ticket", err: errors.New(`ent: missing required edge "SupportTicketMessage.ticket"`)}
	}
	return nil
}

func (_c *SupportTicketMessageCreate) sqlSave(ctx context.Context) (*SupportTicketMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupportTicketMessageCreate) createSpec() (*SupportTicketMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportTicketMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supportticketmessage.Table, sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AuthorID(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorID, field.TypeInt64, value)
		_node.AuthorID = &value
	}
	if value, ok := _c.mutation.AuthorRole(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorRole, field.TypeString, value)
		_node.AuthorRole = value
	}
	if value, ok := _c.mutation.AuthorEmail(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorEmail, field.TypeString, value)
		_node.AuthorEmail = value
	}
	if value, ok := _c.mutation.AuthorName(); ok {
		_spec.SetField(supportticketmessage.FieldAuthorName, field.TypeString, value)
		_node.AuthorName = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(supportticketmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supportticketmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TicketIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticketmessage.TicketTable,
			Columns: []string{supportticketmessage.TicketColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TicketID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicketMessage.Create().
//		SetTicketID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketMessageUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketMessageCreate) OnConflict(opts ...sql.ConflictOption) *SupportTicketMessageUpsertOne {
	_c.conflict = opts
	return &SupportTicketMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicketMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketMessageCreate) OnConflictColumns(columns ...string) *SupportTicketMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketMessageUpsertOne{
		create: _c,
	}
}

type (
	// SupportTicketMessageUpsertOne is the builder for "upsert"-ing
	//  one SupportTicketMessage node.
	SupportTicketMessageUpsertOne struct {
		create *SupportTicketMessageCreate
	}

	// SupportTicketMessageUpsert is the "OnConflict" setter.
	SupportTicketMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetTicketID sets the "ticket_id" field.
func (u *SupportTicketMessageUpsert) SetTicketID(v int64) *SupportTicketMessageUpsert {
	u.Set(supportticketmessage.FieldTicketID, v)
	return u
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *SupportTicketMessageUpsert) UpdateTicketID() *SupportTicketMessageUpsert {
	u.SetExcluded(supportticketmessage.FieldTicketID)
	return u
}

// SetAuthorID sets the "author_id" field.
func (u *SupportTicketMessageUpsert) SetAuthorID(v int64) *SupportTicketMessageUpsert {
	u.Set(supportticketmessage.FieldAuthorID, v)
	return u
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *SupportTicketMessageUpsert) UpdateAuthorID() *SupportTicketMessageUpsert {
	u.SetExcluded(supportticketmessage.FieldAuthorID)
	return u
}

// AddAuthorID adds v to the "author_id" field.
func (u *SupportTicketMessageUpsert) AddAuthorID(v int64) *SupportTicketMessageUpsert {
	u.Add(supportticketmessage.FieldAuthorID, v)
	return u
}

// ClearAuthorID clears the value of the "author_id" field.
func (u *SupportTicketMessageUpsert) ClearAuthorID() *SupportTicketMessageUpsert {
	u.SetNull(supportticketmessage.FieldAuthorID)
	return u
}

// SetAuthorRole sets the "author_role" field.
func (u *SupportTicketMessageUpsert) SetAuthorRole(v string) *SupportTicketMessageUpsert {
	u.Set(supportticketmessage.FieldAuthorRole, v)
	return u
}

// UpdateAuthorRole sets the "author_role" field to the value that was provided on create.
func (u *SupportTicketMessageUpsert) UpdateAuthorRole() *SupportTicketMessageUpsert {
	u.SetExcluded(supportticketmessage.FieldAuthorRole)
	return u
}

// SetAuthorEmail sets the "author_email" field.
func (u *SupportTicketMessageUpsert) SetAuthorEmail(v string) *SupportTicketMessageUpsert {
	u.Set(supportticketmessage.FieldAuthorEmail, v)
	return u
}

// UpdateAuthorEmail sets the "author_email" field to the value that was provided on create.
func (u *SupportTicketMessageUpsert) UpdateAuthorEmail() *SupportTicketMessageUpsert {
	u.SetExcluded(supportticketmessage.FieldAuthorEmail)
	return u
}

// ClearAuthorEmail clears the value of the "author_email" field.
func (u *SupportTicketMessageUpsert) ClearAuthorEmail() *SupportTicketMessageUpsert {
	u.SetNull(supportticketmessage.FieldAuthorEmail)
	return u
}

// SetAuthorName sets the "author_name" field.
func (u *SupportTicketMessageUpsert) SetAuthorName(v string) *SupportTicketMessageUpsert {
	u.Set(supportticketmessage.FieldAuthorName, v)
	return u
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *SupportTicketMessageUpsert) UpdateAuthorName() *SupportTicketMessageUpsert {
	u.SetExcluded(supportticketmessage.FieldAuthorName)
	return u
}

// ClearAuthorName clears the value of the "author_name" field.
func (u *SupportTicketMessageUpsert) ClearAuthorName() *SupportTicketMessageUpsert {
	u.SetNull(supportticketmessage.FieldAuthorName)
	return u
}

// SetContent sets the "content" field.
func (u *SupportTicketMessageUpsert) SetContent(v string) *SupportTicketMessageUpsert {
	u.Set(supportticketmessage.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SupportTicketMessageUpsert) UpdateContent() *SupportTicketMessageUpsert {
	u.SetExcluded(supportticketmessage.FieldContent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupportTicketMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketMessageUpsertOne) UpdateNewValues() *SupportTicketMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supportticketmessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicketMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupportTicketMessageUpsertOne) Ignore() *SupportTicketMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketMessageUpsertOne) DoNothing() *SupportTicketMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketMessageCreate.OnConflict
// documentation for more info.
func (u *SupportTicketMessageUpsertOne) Update(set func(*SupportTicketMessageUpsert)) *SupportTicketMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *SupportTicketMessageUpsertOne) SetTicketID(v int64) *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertOne) UpdateTicketID() *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateTicketID()
	})
}

// SetAuthorID sets the "author_id" field.
func (u *SupportTicketMessageUpsertOne) SetAuthorID(v int64) *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetAuthorID(v)
	})
}

// AddAuthorID adds v to the "author_id" field.
func (u *SupportTicketMessageUpsertOne) AddAuthorID(v int64) *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.AddAuthorID(v)
	})
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertOne) UpdateAuthorID() *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateAuthorID()
	})
}

// ClearAuthorID clears the value of the "author_id" field.
func (u *SupportTicketMessageUpsertOne) ClearAuthorID() *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.ClearAuthorID()
	})
}

// SetAuthorRole sets the "author_role" field.
func (u *SupportTicketMessageUpsertOne) SetAuthorRole(v string) *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetAuthorRole(v)
	})
}

// UpdateAuthorRole sets the "author_role" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertOne) UpdateAuthorRole() *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateAuthorRole()
	})
}

// SetAuthorEmail sets the "author_email" field.
func (u *SupportTicketMessageUpsertOne) SetAuthorEmail(v string) *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetAuthorEmail(v)
	})
}

// UpdateAuthorEmail sets the "author_email" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertOne) UpdateAuthorEmail() *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateAuthorEmail()
	})
}

// ClearAuthorEmail clears the value of the "author_email" field.
func (u *SupportTicketMessageUpsertOne) ClearAuthorEmail() *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.ClearAuthorEmail()
	})
}

// SetAuthorName sets the "author_name" field.
func (u *SupportTicketMessageUpsertOne) SetAuthorName(v string) *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetAuthorName(v)
	})
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertOne) UpdateAuthorName() *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateAuthorName()
	})
}

// ClearAuthorName clears the value of the "author_name" field.
func (u *SupportTicketMessageUpsertOne) ClearAuthorName() *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.ClearAuthorName()
	})
}

// SetContent sets the "content" field.
func (u *SupportTicketMessageUpsertOne) SetContent(v string) *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertOne) UpdateContent() *SupportTicketMessageUpsertOne {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateContent()
	})
}

// Exec executes the query.
func (u *SupportTicketMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupportTicketMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupportTicketMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupportTicketMessageCreateBulk is the builder for creating many SupportTicketMessage entities in bulk.
type SupportTicketMessageCreateBulk struct {
	config
	err      error
	builders []*SupportTicketMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the SupportTicketMessage entities in the database.
func (_c *SupportTicketMessageCreateBulk) Save(ctx context.Context) ([]*SupportTicketMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupportTicketMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportTicketMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupportTicketMessageCreateBulk) SaveX(ctx context.Context) []*SupportTicketMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportTicketMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportTicketMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportTicketMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportTicketMessageUpsert) {
//			SetTicketID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportTicketMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupportTicketMessageUpsertBulk {
	_c.conflict = opts
	return &SupportTicketMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportTicketMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportTicketMessageCreateBulk) OnConflictColumns(columns ...string) *SupportTicketMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportTicketMessageUpsertBulk{
		create: _c,
	}
}

// SupportTicketMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of SupportTicketMessage nodes.
type SupportTicketMessageUpsertBulk struct {
	create *SupportTicketMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupportTicketMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupportTicketMessageUpsertBulk) UpdateNewValues() *SupportTicketMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supportticketmessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportTicketMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupportTicketMessageUpsertBulk) Ignore() *SupportTicketMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportTicketMessageUpsertBulk) DoNothing() *SupportTicketMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportTicketMessageCreateBulk.OnConflict
// documentation for more info.
func (u *SupportTicketMessageUpsertBulk) Update(set func(*SupportTicketMessageUpsert)) *SupportTicketMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportTicketMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetTicketID sets the "ticket_id" field.
func (u *SupportTicketMessageUpsertBulk) SetTicketID(v int64) *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetTicketID(v)
	})
}

// UpdateTicketID sets the "ticket_id" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertBulk) UpdateTicketID() *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateTicketID()
	})
}

// SetAuthorID sets the "author_id" field.
func (u *SupportTicketMessageUpsertBulk) SetAuthorID(v int64) *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetAuthorID(v)
	})
}

// AddAuthorID adds v to the "author_id" field.
func (u *SupportTicketMessageUpsertBulk) AddAuthorID(v int64) *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.AddAuthorID(v)
	})
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertBulk) UpdateAuthorID() *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateAuthorID()
	})
}

// ClearAuthorID clears the value of the "author_id" field.
func (u *SupportTicketMessageUpsertBulk) ClearAuthorID() *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.ClearAuthorID()
	})
}

// SetAuthorRole sets the "author_role" field.
func (u *SupportTicketMessageUpsertBulk) SetAuthorRole(v string) *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetAuthorRole(v)
	})
}

// UpdateAuthorRole sets the "author_role" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertBulk) UpdateAuthorRole() *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateAuthorRole()
	})
}

// SetAuthorEmail sets the "author_email" field.
func (u *SupportTicketMessageUpsertBulk) SetAuthorEmail(v string) *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetAuthorEmail(v)
	})
}

// UpdateAuthorEmail sets the "author_email" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertBulk) UpdateAuthorEmail() *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateAuthorEmail()
	})
}

// ClearAuthorEmail clears the value of the "author_email" field.
func (u *SupportTicketMessageUpsertBulk) ClearAuthorEmail() *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.ClearAuthorEmail()
	})
}

// SetAuthorName sets the "author_name" field.
func (u *SupportTicketMessageUpsertBulk) SetAuthorName(v string) *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetAuthorName(v)
	})
}

// UpdateAuthorName sets the "author_name" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertBulk) UpdateAuthorName() *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateAuthorName()
	})
}

// ClearAuthorName clears the value of the "author_name" field.
func (u *SupportTicketMessageUpsertBulk) ClearAuthorName() *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.ClearAuthorName()
	})
}

// SetContent sets the "content" field.
func (u *SupportTicketMessageUpsertBulk) SetContent(v string) *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SupportTicketMessageUpsertBulk) UpdateContent() *SupportTicketMessageUpsertBulk {
	return u.Update(func(s *SupportTicketMessageUpsert) {
		s.UpdateContent()
	})
}

// Exec executes the query.
func (u *SupportTicketMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupportTicketMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportTicketMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportTicketMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
