// Code generated by ent, DO NOT EDIT.

package supportticketmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldID, id))
}

// TicketID applies equality check predicate on the "ticket_id" field. It's identical to TicketIDEQ.
func TicketID(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// AuthorID applies equality check predicate on the "author_id" field. It's identical to AuthorIDEQ.
func AuthorID(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorRole applies equality check predicate on the "author_role" field. It's identical to AuthorRoleEQ.
func AuthorRole(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorRole, v))
}

// AuthorEmail applies equality check predicate on the "author_email" field. It's identical to AuthorEmailEQ.
func AuthorEmail(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorEmail, v))
}

// AuthorName applies equality check predicate on the "author_name" field. It's identical to AuthorNameEQ.
func AuthorName(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorName, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldContent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// TicketIDEQ applies the EQ predicate on the "ticket_id" field.
func TicketIDEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldTicketID, v))
}

// TicketIDNEQ applies the NEQ predicate on the "ticket_id" field.
func TicketIDNEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldTicketID, v))
}

// TicketIDIn applies the In predicate on the "ticket_id" field.
func TicketIDIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldTicketID, vs...))
}

// TicketIDNotIn applies the NotIn predicate on the "ticket_id" field.
func TicketIDNotIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldTicketID, vs...))
}

// AuthorIDEQ applies the EQ predicate on the "author_id" field.
func AuthorIDEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorID, v))
}

// AuthorIDNEQ applies the NEQ predicate on the "author_id" field.
func AuthorIDNEQ(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldAuthorID, v))
}

// AuthorIDIn applies the In predicate on the "author_id" field.
func AuthorIDIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldAuthorID, vs...))
}

// AuthorIDNotIn applies the NotIn predicate on the "author_id" field.
func AuthorIDNotIn(vs ...int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldAuthorID, vs...))
}

// AuthorIDGT applies the GT predicate on the "author_id" field.
func AuthorIDGT(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldAuthorID, v))
}

// AuthorIDGTE applies the GTE predicate on the "author_id" field.
func AuthorIDGTE(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldAuthorID, v))
}

// AuthorIDLT applies the LT predicate on the "author_id" field.
func AuthorIDLT(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldAuthorID, v))
}

// AuthorIDLTE applies the LTE predicate on the "author_id" field.
func AuthorIDLTE(v int64) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldAuthorID, v))
}

// AuthorIDIsNil applies the IsNil predicate on the "author_id" field.
func AuthorIDIsNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIsNull(FieldAuthorID))
}

// AuthorIDNotNil applies the NotNil predicate on the "author_id" field.
func AuthorIDNotNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotNull(FieldAuthorID))
}

// AuthorRoleEQ applies the EQ predicate on the "author_role" field.
func AuthorRoleEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorRole, v))
}

// AuthorRoleNEQ applies the NEQ predicate on the "author_role" field.
func AuthorRoleNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldAuthorRole, v))
}

// AuthorRoleIn applies the In predicate on the "author_role" field.
func AuthorRoleIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldAuthorRole, vs...))
}

// AuthorRoleNotIn applies the NotIn predicate on the "author_role" field.
func AuthorRoleNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldAuthorRole, vs...))
}

// AuthorRoleGT applies the GT predicate on the "author_role" field.
func AuthorRoleGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldAuthorRole, v))
}

// AuthorRoleGTE applies the GTE predicate on the "author_role" field.
func AuthorRoleGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldAuthorRole, v))
}

// AuthorRoleLT applies the LT predicate on the "author_role" field.
func AuthorRoleLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldAuthorRole, v))
}

// AuthorRoleLTE applies the LTE predicate on the "author_role" field.
func AuthorRoleLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldAuthorRole, v))
}

// AuthorRoleContains applies the Contains predicate on the "author_role" field.
func AuthorRoleContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldAuthorRole, v))
}

// AuthorRoleHasPrefix applies the HasPrefix predicate on the "author_role" field.
func AuthorRoleHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldAuthorRole, v))
}

// AuthorRoleHasSuffix applies the HasSuffix predicate on the "author_role" field.
func AuthorRoleHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldAuthorRole, v))
}

// AuthorRoleEqualFold applies the EqualFold predicate on the "author_role" field.
func AuthorRoleEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldAuthorRole, v))
}

// AuthorRoleContainsFold applies the ContainsFold predicate on the "author_role" field.
func AuthorRoleContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldAuthorRole, v))
}

// AuthorEmailEQ applies the EQ predicate on the "author_email" field.
func AuthorEmailEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorEmail, v))
}

// AuthorEmailNEQ applies the NEQ predicate on the "author_email" field.
func AuthorEmailNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldAuthorEmail, v))
}

// AuthorEmailIn applies the In predicate on the "author_email" field.
func AuthorEmailIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldAuthorEmail, vs...))
}

// AuthorEmailNotIn applies the NotIn predicate on the "author_email" field.
func AuthorEmailNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldAuthorEmail, vs...))
}

// AuthorEmailGT applies the GT predicate on the "author_email" field.
func AuthorEmailGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldAuthorEmail, v))
}

// AuthorEmailGTE applies the GTE predicate on the "author_email" field.
func AuthorEmailGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldAuthorEmail, v))
}

// AuthorEmailLT applies the LT predicate on the "author_email" field.
func AuthorEmailLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldAuthorEmail, v))
}

// AuthorEmailLTE applies the LTE predicate on the "author_email" field.
func AuthorEmailLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldAuthorEmail, v))
}

// AuthorEmailContains applies the Contains predicate on the "author_email" field.
func AuthorEmailContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldAuthorEmail, v))
}

// AuthorEmailHasPrefix applies the HasPrefix predicate on the "author_email" field.
func AuthorEmailHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldAuthorEmail, v))
}

// AuthorEmailHasSuffix applies the HasSuffix predicate on the "author_email" field.
func AuthorEmailHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldAuthorEmail, v))
}

// AuthorEmailIsNil applies the IsNil predicate on the "author_email" field.
func AuthorEmailIsNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIsNull(FieldAuthorEmail))
}

// AuthorEmailNotNil applies the NotNil predicate on the "author_email" field.
func AuthorEmailNotNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotNull(FieldAuthorEmail))
}

// AuthorEmailEqualFold applies the EqualFold predicate on the "author_email" field.
func AuthorEmailEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldAuthorEmail, v))
}

// AuthorEmailContainsFold applies the ContainsFold predicate on the "author_email" field.
func AuthorEmailContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldAuthorEmail, v))
}

// AuthorNameEQ applies the EQ predicate on the "author_name" field.
func AuthorNameEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldAuthorName, v))
}

// AuthorNameNEQ applies the NEQ predicate on the "author_name" field.
func AuthorNameNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldAuthorName, v))
}

// AuthorNameIn applies the In predicate on the "author_name" field.
func AuthorNameIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldAuthorName, vs...))
}

// AuthorNameNotIn applies the NotIn predicate on the "author_name" field.
func AuthorNameNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldAuthorName, vs...))
}

// AuthorNameGT applies the GT predicate on the "author_name" field.
func AuthorNameGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldAuthorName, v))
}

// AuthorNameGTE applies the GTE predicate on the "author_name" field.
func AuthorNameGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldAuthorName, v))
}

// AuthorNameLT applies the LT predicate on the "author_name" field.
func AuthorNameLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldAuthorName, v))
}

// AuthorNameLTE applies the LTE predicate on the "author_name" field.
func AuthorNameLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldAuthorName, v))
}

// AuthorNameContains applies the Contains predicate on the "author_name" field.
func AuthorNameContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldAuthorName, v))
}

// AuthorNameHasPrefix applies the HasPrefix predicate on the "author_name" field.
func AuthorNameHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldAuthorName, v))
}

// AuthorNameHasSuffix applies the HasSuffix predicate on the "author_name" field.
func AuthorNameHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldAuthorName, v))
}

// AuthorNameIsNil applies the IsNil predicate on the "author_name" field.
func AuthorNameIsNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIsNull(FieldAuthorName))
}

// AuthorNameNotNil applies the NotNil predicate on the "author_name" field.
func AuthorNameNotNil() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotNull(FieldAuthorName))
}

// AuthorNameEqualFold applies the EqualFold predicate on the "author_name" field.
func AuthorNameEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldAuthorName, v))
}

// AuthorNameContainsFold applies the ContainsFold predicate on the "author_name" field.
func AuthorNameContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldAuthorName, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldContainsFold(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTicket applies the HasEdge predicate on the "ticket" edge.
func HasTicket() predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TicketTable, TicketColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTicketWith applies the HasEdge predicate on the "ticket" edge with a given conditions (other predicates).
func HasTicketWith(preds ...predicate.SupportTicket) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(func(s *sql.Selector) {
		step := newTicketStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportTicketMessage) predicate.SupportTicketMessage {
	return predicate.SupportTicketMessage(sql.NotPredicates(p))
}
